name: QUIC Interop run LibreSSL picoquic

run-name: Run on picoquic

on: 
  workflow_dispatch:
             
jobs:
  run:
    runs-on: ubuntu-24.04
  
    steps:
      - uses: actions/checkout@v4

      - name: Install tshark
        run: |
          sudo apt-get update
          sudo apt-get -y install tshark

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository }}:libressl

      - name: Run
        run: |
          git clone https://github.com/quic-interop/quic-interop-runner
          cd quic-interop-runner
          pip install -r requirements.txt --break-system-packages
          python run.py -l logs -r haproxy=ghcr.io/${{ github.repository }}:libressl -t handshake,transfer,longrtt,multiplexing,retry,http3,blackhole,amplificationlimit,handshakeloss,transferloss,handshakecorruption,transfercorruption,v2,goodput,crosstraffic -c picoquic -s haproxy

      - name: Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: quic-interop-runner/logs/



