name: QUIC Interop Build img Angie LibreSSL

on: 
  workflow_dispatch:
              
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          git clone https://github.com/chipitsine/angie-quic-qns-libressl

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: angie-quic-qns-libressl
          push: true
          tags: ghcr.io/${{ github.repository }}:angie-libressl
