name: QUIC Interop run angie BoringSSL / picoquic

on: 
  workflow_dispatch:
             
jobs:
  run:
    strategy:
      matrix:
        suite: [
          { client: picoquic, tests: "amplificationlimit" }
          ]
      fail-fast: false
  
    runs-on: ubuntu-24.04
  
    steps:
      - uses: actions/checkout@v4

      - name: Install tshark
        run: |
          sudo apt-get update
          sudo apt-get -y install tshark

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository }}:angie

      - name: Run
        run: |
          git clone https://github.com/quic-interop/quic-interop-runner
          cd quic-interop-runner
          pip install -r requirements.txt --break-system-packages
          python run.py --debug -l logs -t ${{ matrix.suite.tests }} -c ${{ matrix.suite.client }} -s nginx -r nginx=ghcr.io/${{ github.repository }}:angie

      - name: Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: quic-interop-runner/logs/
