name: QUIC Interop run QuicTLS go ASAN

on: 
  workflow_dispatch:
             
jobs:
  run:
    strategy:
      matrix:
        suite: [
          { client: quic-go,  tests: "handshake,transfer,longrtt,chacha20,multiplexing,retry,resumption,zerortt,http3,blackhole,keyupdate,ecn,amplificationlimit,handshakeloss,transferloss,handshakecorruption,transfercorruption,ipv6,v2,goodput,crosstraffic" }
        ]
      fail-fast: false
  
    runs-on: ubuntu-24.04
  
    steps:
      - uses: actions/checkout@v4

      - name: Install tshark
        run: |
          sudo apt-get update
          sudo apt-get -y install tshark

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository }}:quictls-asan

      - name: Run
        run: |
          git clone https://github.com/quic-interop/quic-interop-runner
          cd quic-interop-runner
          pip install -r requirements.txt --break-system-packages
          python run.py -l logs -r haproxy=ghcr.io/${{ github.repository }}:quictls-asan -t ${{ matrix.suite.tests }} -c ${{ matrix.suite.client }} -s haproxy

      - name: Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: quic-interop-runner/logs/
